apiVersion: serving.knative.dev/v1
kind: Service
metadata:
 name: helloworld-go
 namespace: default
spec:
 template:
  spec:
   containers:
    - image: index.docker.io/reoring/helloworld-go:v1
      env:
        - name: TARGET
          value: "Go Sample v1"
