apiVersion: serving.knative.dev/v1
kind: Service
metadata:
 name: helloworld-go
 namespace: default
spec:
 template:
  spec:
   containers:
    - image: reg.reoring.dev/test/helloworlg-go:latest
      env:
        - name: TARGET
          value: "Go Sample v1"
