apiVersion: serving.knative.dev/v1
kind: Service
metadata:
 name: helloworld-go
 namespace: default
spec:
 template:
  spec:
   containers:
    - image: my-release-harbor-core.default.svc.cluster.local:80/test/helloworld-go:latest
      env:
        - name: TARGET
          value: "Go Sample v1"
